# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'shuqireader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    install_all_flutter_pods(flutter_application_path)
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'ESTabBarController-swift'
    pod 'FSPagerView'
    pod 'Moya'
    pod 'HandyJSON', '5.0.0-beta'
    pod 'SwiftyJSON'
    pod 'DNSPageView'
    pod 'JXMarqueeView'
    pod 'LTScrollView'
    pod 'MJRefresh'
    #pod 'SkeletonView'
    pod 'SwiftMessages'
    pod 'FDFullscreenPopGesture', '1.1'

    #pod 'YYKit'
    pod 'SVProgressHUD'
    pod 'StreamingKit'
    pod 'ObjectMapper'
    pod 'ESPullToRefresh'
#    pod 'RealmSwift'
#    pod 'Realm'
#    pod 'GRDB.swift'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'ATKit_Swift',    :git => 'https://github.com/tianya2416/ATKit_Swift.git'
    pod 'DZNEmptyDataSet'
    pod 'YYCategories'
    pod 'MBProgressHUD',:git => 'https://github.com/tianya2416/MBProgress.git'
    pod 'YYCache'

end
